### ISSUE TITLE
about Compute resource

### ISSUE THREAD

**Issue by everRoc** [XiaoyuShi97/VideoFlow#1]
Great work! I'm curious about the GPUs you used to finish the experiment. Can you tell me more about it?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. To train the model, you need 24G GPU. This requirement is lower if replacing the twins encoder with a lighter encoder.

**Comment by everRoc** [comment]
您好，您的邮件我已经收到了，谢谢
