### ISSUE TITLE
higher cuda and torch version

### ISSUE THREAD

**Issue by ZhaoqunZhong** [XiaoyuShi97/VideoFlow#11]
Hi, 
Another problem, I'm using cuda11.6 + torch 1.12. When I run the BOF mode with 3 images, I got this error 
```
[Using twins as context encoder]
[Using twins as feature encoder]
[Using GMA-SK2]
[Using corr_fn default]
VideoFlow_ckpt/BOF_kitti.pth
Parameter Count: 12659389
preparing image...
Input image sequence dir = /home/sti/Downloads/VideoFlow/test/images
/home/sti/anaconda3/envs/limap/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352657443/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```
Do I have to use the exact torch/torchvision/cudatoolkit version? I think it's pretty difficult since these version combinations are a little old. 
And my configs/kitti.py file is like this
```
from yacs.config import CfgNode as CN
_CN = CN()

_CN.name = ''
_CN.suffix =''
_CN.gamma = 0.85
_CN.max_flow = 400
_CN.batch_size = 8
_CN.sum_freq = 100
_CN.val_freq = 100000000
_CN.image_size = [1080, 720]
_CN.add_noise = False
_CN.use_smoothl1 = False
_CN.critical_params = []

_CN.network = 'BOFNet'
_CN.mixed_precision = False
_CN.filter_epe = False


_CN.restore_ckpt = None

_CN.model = "VideoFlow_ckpt/BOF_kitti.pth"



_CN.BOFNet = CN()
_CN.BOFNet.pretrain = True
_CN.BOFNet.cnet = 'twins'
_CN.BOFNet.fnet = 'twins'
_CN.BOFNet.gma = 'GMA-SK2'
_CN.BOFNet.corr_fn = "default"
_CN.BOFNet.mixed_precision = False

_CN.BOFNet.decoder_depth = 12
_CN.BOFNet.critical_params = ["cnet", "fnet", "pretrain", "corr_fn", "mixed_precision"]

### TRAINER
_CN.trainer = CN()
_CN.trainer.scheduler = 'OneCycleLR'
_CN.trainer.optimizer = 'adamw'
_CN.trainer.canonical_lr = 12.5e-5
_CN.trainer.adamw_decay = 1e-4
_CN.trainer.clip = 1.0
_CN.trainer.num_steps = 80000
_CN.trainer.epsilon = 1e-8
_CN.trainer.anneal_strategy = 'linear'
def get_cfg():
    return _CN.clone()
```
Really want to see the performance of this repo, but haven't got it to work no matter how😂

**Comment by XiaoyuShi97** [comment]
As long as you can run the code, the version does not matter. Let me update the efficient implementation this weekend.

**Comment by jeffreychou777** [comment]
> Hi, Another problem, I'm using cuda11.6 + torch 1.12. When I run the BOF mode with 3 images, I got this error
> 
> ```
> [Using twins as context encoder]
> [Using twins as feature encoder]
> [Using GMA-SK2]
> [Using corr_fn default]
> VideoFlow_ckpt/BOF_kitti.pth
> Parameter Count: 12659389
> preparing image...
> Input image sequence dir = /home/sti/Downloads/VideoFlow/test/images
> /home/sti/anaconda3/envs/limap/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352657443/work/aten/src/ATen/native/TensorShape.cpp:2894.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> ```
> 
> Do I have to use the exact torch/torchvision/cudatoolkit version? I think it's pretty difficult since these version combinations are a little old. And my configs/kitti.py file is like this
> 
> ```
> from yacs.config import CfgNode as CN
> _CN = CN()
> 
> _CN.name = ''
> _CN.suffix =''
> _CN.gamma = 0.85
> _CN.max_flow = 400
> _CN.batch_size = 8
> _CN.sum_freq = 100
> _CN.val_freq = 100000000
> _CN.image_size = [1080, 720]
> _CN.add_noise = False
> _CN.use_smoothl1 = False
> _CN.critical_params = []
> 
> _CN.network = 'BOFNet'
> _CN.mixed_precision = False
> _CN.filter_epe = False
> 
> 
> _CN.restore_ckpt = None
> 
> _CN.model = "VideoFlow_ckpt/BOF_kitti.pth"
> 
> 
> 
> _CN.BOFNet = CN()
> _CN.BOFNet.pretrain = True
> _CN.BOFNet.cnet = 'twins'
> _CN.BOFNet.fnet = 'twins'
> _CN.BOFNet.gma = 'GMA-SK2'
> _CN.BOFNet.corr_fn = "default"
> _CN.BOFNet.mixed_precision = False
> 
> _CN.BOFNet.decoder_depth = 12
> _CN.BOFNet.critical_params = ["cnet", "fnet", "pretrain", "corr_fn", "mixed_precision"]
> 
> ### TRAINER
> _CN.trainer = CN()
> _CN.trainer.scheduler = 'OneCycleLR'
> _CN.trainer.optimizer = 'adamw'
> _CN.trainer.canonical_lr = 12.5e-5
> _CN.trainer.adamw_decay = 1e-4
> _CN.trainer.clip = 1.0
> _CN.trainer.num_steps = 80000
> _CN.trainer.epsilon = 1e-8
> _CN.trainer.anneal_strategy = 'linear'
> def get_cfg():
>     return _CN.clone()
> ```
> 
> Really want to see the performance of this repo, but haven't got it to work no matter how😂

Hi, I had the same problem as you with a higher version of torch, could you please tell me how you finally solved it. Thanks!

**Comment by delldu** [comment]
use meshgrid(..., indexing="ij") instead of meshgrid(...)

**Comment by jeffreychou777** [comment]
> use meshgrid(..., indexing="ij") instead of meshgrid(...)

Thanks for the reply though I have resolved the issue.
