### ISSUE TITLE
Domain adaptability

### ISSUE THREAD

**Issue by chenglinh** [XiaoyuShi97/VideoFlow#12]
Hi, thank you for the inspiring work! 

I am wondering how is the ability of the pre-trained model for domain adaptation. (e.g. performing optical flow estimation on arbitrary real-world video)

Since the performance improves a lot when the model is fine-tuned on Sintel and KITTI, how well do you think the pre-trained model would perform on the unseen datasets?

If I would like to apply the method in VideoFlow on different video sets, is it possible to leverage the model trained on "C+T+S+K+H"?  Otherwise, what method would you suggest for such scenario?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. We tested VideoFlow on Davis and some animation videos and it works well. You can compare BOF and MOF by visualizing the predictions on your own dataset and choose the better one, As for the checkpoint, I recommend to use sintel.ckpt for general purposes and choose kitti.ckpt if your case is a typical driving scenario. Let me know if you have further questions.
