### ISSUE TITLE
Unable to find dataset.py

### ISSUE THREAD

**Issue by MrFahad** [XiaoyuShi97/VideoFlow#13]
Hi, I am trying to run training, but every time I am getting PATH_TO_FINAL/final error. Though I have created a datasets folder and inside that folder I placed Sintel and KITTI datasets. 

Guide me please.

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. Do you refer to this line? https://github.com/XiaoyuShi97/VideoFlow/blob/main/configs/sintel_multiframes.py#L18 This specifies the path to the restored checkpoint from last stage. For example, in the sintel stage, this should be things_MOF.pth or your trained checkpoint. Let me know if there are other questions.

**Comment by MrFahad** [comment]
Thanks for your reply, I tried with sintel_MOF.pth for the sintel dataset. But it shows me error, I will try with things_MOF.pth today. I am planning to train it for my own dataset later on.

---
Regards,

(Fahad Majeed)
PhD Scholar,
College of Science and Engineering
Hamad Bin Khalifa University, Doha, Qatar
https://www.hbku.edu.qa/en
________________________________

**Comment by XiaoyuShi97** [comment]
Hi. things_MOF.pth and sintel_MOF.pth should make no difference. You can show me the detailed error messages. And you are right to resume the sintel stage model (rather than things stage) to finetune on your own dataset.

**Comment by MrFahad** [comment]
Because in the model link there are only 4 .pth files. I created a datasets folder and inside that folder I put sintel and KITTI datasets respectively.

---
Regards,

(Fahad Majeed)
PhD Scholar,
College of Science and Engineering
Hamad Bin Khalifa University, Doha, Qatar
https://www.hbku.edu.qa/en
________________________________

**Comment by MrFahad** [comment]
`python -u train_MOFNet.py --name MOF-sintel --stage sintel --validation sintel
2023-09-13 12:25:36.870 | INFO     | __main__:<module>:130 - MOFNetStack:
  Tfusion: stack
  cnet: twins
  context_3D: False
  corr_fn: default
  corr_levels: 4
  critical_params: ['cnet', 'fnet', 'pretrain', 'corr_fn', 'Tfusion', 'corr_levels', 'decoder_depth', 'mixed_precision']
  decoder_depth: 12
  down_ratio: 8
  feat_dim: 256
  fnet: twins
  mixed_precision: True
  pretrain: True
add_noise: False
batch_size: 8
critical_params: []
filter_epe: False
gamma: 0.85
image_size: [432, 960]
input_frames: 5
log_dir: logs/MOF-sintel/MOFNetStack/cnet[twins]fnet[twins]pretrain[True]corr_fn[default]Tfusion[stack]corr_levels[4]decoder_depth[12]mixed_precision[True](09_13_12_25)
max_flow: 400
mixed_precision: True
name: MOF-sintel
network: MOFNetStack
restore_ckpt: VideoFlow_ckpt/MOF_sintel.pth
stage: sintel
suffix: 
sum_freq: 100
trainer:
  adamw_decay: 0.0001
  anneal_strategy: linear
  canonical_lr: 0.000125
  clip: 1.0
  epsilon: 1e-08
  num_steps: 40000
  optimizer: adamw
  scheduler: OneCycleLR
use_smoothl1: False
val_freq: 100000000
validation: ['sintel']
[Using twins as context encoder]
[Using twins as feature encoder]
[Using stack.]
[Using corr_fn default]
2023-09-13 12:25:38.774 | INFO     | __main__:train:58 - Parameter Count: 13453240
[Loading ckpt from VideoFlow_ckpt/MOF_sintel.pth]
[input frame number is 5]
[reverse_rate is 0.3]
2239 2239 2239
[['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0006.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0007.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0008.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0010.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0007.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0008.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0010.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0011.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0008.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0010.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0011.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0012.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0010.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0011.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0012.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0013.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0010.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0011.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0012.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0013.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0014.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0011.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0012.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0013.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0014.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0000/left/0015.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0006.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0007.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0008.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0010.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0007.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0008.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0010.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0011.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0008.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0010.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0011.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0012.png'], ['datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0009.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0010.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0011.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0012.png', 'datasets/FlyingThings3Dflow_data/frames_cleanpass/TRAIN/A/0001/left/0013.png']]
[['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0007_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0007_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0009_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0010_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0011_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0012_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0012_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0012_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0013_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0012_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0013_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0012_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0013_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0014_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0012_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0013_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0000/into_past/left/OpticalFlowIntoPast_0014_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0007_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0007_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0009_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0008_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0010_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0009_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0011_L.pfm'], ['datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_future/left/OpticalFlowIntoFuture_0012_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0010_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0011_L.pfm', 'datasets/FlyingThings3Dflow_data/optical_flow/TRAIN/A/0001/into_past/left/OpticalFlowIntoPast_0012_L.pfm']]
[[True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True], [True, True, True, True, True, True]]
[input frame number is 5]
[reverse_rate is 0.3]
23 23
[input frame number is 5]
[reverse_rate is 0.3]
23 23
[input frame number is 5]
[reverse_rate is 0.3]
36 36
[input frame number is 5]
[reverse_rate is 0.3]
[dataset len: ] 13434 995 975 600
Training with 247309 image pairs
[ WARN:0@3.203] global loadsave.cpp:248 findDecoder imread_('datasets/KITTI/HD1K/hd1k_flow_gt/flow_occ/000012_0071.png'): can't open/read file: check file path/integrity
[ WARN:0@3.204] global loadsave.cpp:248 findDecoder imread_('datasets/KITTI/KITTI/training/flow_occ/000042_10.png'): can't open/read file: check file path/integrity
[ WARN:0@3.208] global loadsave.cpp:248 findDecoder imread_('datasets/KITTI/KITTI/training/flow_occ/000113_10.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/home/fahad/Desktop/VideoFlow/train_MOFNet.py", line 135, in <module>
    train(cfg)
  File "/home/fahad/Desktop/VideoFlow/train_MOFNet.py", line 77, in train
    for i_batch, data_blob in enumerate(train_loader):
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/_utils.py", line 644, in reraise
[ WARN:0@3.209] global loadsave.cpp:248 findDecoder imread_('datasets/KITTI/KITTI/training/flow_occ/000118_10.png'): can't open/read file: check file path/integrity
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 243, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/videoflow/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 243, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/core/datasets_multiframes.py", line 74, in __getitem__
    flow, valid = frame_utils.readFlowKITTI(self.flow_list[index][idx])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/core/utils/frame_utils.py", line 104, in readFlowKITTI
    flow = flow[:,:,::-1].astype(np.float32)
           ~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
`

**Comment by XiaoyuShi97** [comment]
Please double check if datasets/KITTI/KITTI/training/flow_occ/000042_10.png this path is correct.

**Comment by MrFahad** [comment]
But in my directory, the path is datasets/KITTI/KITTI/training/images_2/000042_10.png

**Comment by XiaoyuShi97** [comment]
Please download the multi-view KITTI datasets from https://www.cvlibs.net/datasets/kitti/eval_scene_flow.php

**Comment by MrFahad** [comment]
Yes, I have downloaded it before from the same link. The dataset is about 14 GB.

**Comment by XiaoyuShi97** [comment]
Ohhh. Seems I changed the path name in my server. You can edit the path according to your datasets structure.

**Comment by MrFahad** [comment]
but right now i just want to run training on sintel dataset. I am using the following command for that:

python -u train_MOFNet.py --name MOF-sintel --stage sintel --validation sintel

**Comment by XiaoyuShi97** [comment]
https://github.com/XiaoyuShi97/VideoFlow/blob/main/core/datasets_multiframes.py#L540
The sintel stage uses a combination of several datasets. You can comment out other datasets as you want.

**Comment by MrFahad** [comment]
Please see the below script:

def fetch_dataloader(args, TRAIN_DS='C+T+K+S+H'):
   
    if args.stage == 'sintel':
        aug_params = {'crop_size': args.image_size, 'min_scale': -0.2, 'max_scale': 0.6, 'do_flip': True}
        sintel_clean = MpiSintel(aug_params, dstype='clean', input_frames=args.input_frames)
        sintel_final = MpiSintel(aug_params, dstype='final', input_frames=args.input_frames) 
        print("[dataset len: ]", len(sintel_clean), len(sintel_final))

        train_dataset = 100*sintel_clean + 100*sintel_final

    print('Training with %d image pairs' % len(train_dataset))
    return train_loader

**Comment by XiaoyuShi97** [comment]
Yes, this should work?

**Comment by MrFahad** [comment]
Now I am getting this error: 

 File "/home/fahad/Desktop/VideoFlow/core/datasets_multiframes.py", line 65, in __getitem__
    flow = frame_utils.read_gen(self.flow_list[index][idx])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/core/utils/frame_utils.py", line 130, in read_gen
    return readFlow(file_name).astype(np.float32)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/core/utils/frame_utils.py", line 19, in readFlow
    with open(fn, 'rb') as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Sintel/Sintel/training/flow/bandage_2/frame_0024.flo'

I have checked the directory; the file is available. I don't know why it is showing me this error.

**Comment by XiaoyuShi97** [comment]
Is your path 'datasets/Sintel/Sintel/**' or 'datasets/Sintel/**'?

**Comment by MrFahad** [comment]
I have the same path like datasets/Sintel/Sintel/training/flow/bandage_2/frame_0024.flo'

But I don't know why it showing the error message, though the file is available there.

**Comment by XiaoyuShi97** [comment]
It is so weird. Please double check the path or use absolute path?

**Comment by MrFahad** [comment]
After setting the path, now i am getting the following cuda error:

 File "/home/fahad/Desktop/VideoFlow/core/Networks/MOFNetStack/network.py", line 154, in forward
    backward_corr_fn = CorrBlock(fmaps[:, 1:N-1, ...].reshape(B*(N-2), -1, H//down_ratio, W//down_ratio), fmaps[:, 0:N-2, ...].reshape(B*(N-2), -1, H//down_ratio, W//down_ratio), num_levels=self.cfg.corr_levels, radius=self.cfg.corr_radius)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/core/Networks/MOFNetStack/corr.py", line 66, in __init__
    corr = CorrBlock.corr(fmap1, fmap2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/Desktop/VideoFlow/core/Networks/MOFNetStack/corr.py", line 105, in corr
    corr = torch.matmul(fmap1.transpose(1, 2), fmap2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.88 GiB (GPU 0; 23.68 GiB total capacity; 18.29 GiB already allocated; 85.38 MiB free; 19.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF



Though I have tested with the batch size: 2 and 4 as well.

**Comment by XiaoyuShi97** [comment]
Hi, this is a typical out of memory error. Please try to 1) reduce batch size, 2) decrease training size and 3) use mixed-precision training.

**Comment by MrFahad** [comment]
The script is running perfectly, and I just remembered that I had to tell you. I reduce the batch size and reduce the image resolution as _CN.image_size = [224, 360]   #[432, 960]

**Comment by XiaoyuShi97** [comment]
Glad to hear that!
