### ISSUE TITLE
Strange pattern in smooth areas (e.g., sky)

### ISSUE THREAD

**Issue by ZhihaoHu** [XiaoyuShi97/VideoFlow#14]
Great work! I'm using VideoFlow to extract optical flow for video generation. However, I find that when estimate the optical flow in static areas, some strange patterns will appear in smooth areas (e.g., sky)
The input 5 key frames :
https://github.com/XiaoyuShi97/VideoFlow/assets/30406852/7c150287-eddc-408b-9f62-82612c03c19e

Then the strange pattern will appear in the sky:
![zflow_4_to_5](https://github.com/XiaoyuShi97/VideoFlow/assets/30406852/e2e05469-71e0-4c6f-857d-8eec0221252d)
![zflow_2_to_1](https://github.com/XiaoyuShi97/VideoFlow/assets/30406852/bd37608d-ec94-4b05-b3e8-6d5dc018a26b)

How to avoid this phenomenon?
Can I change some hyperparameter to make the motion in the sky more smoother?
Or should I retrain the model?

Looking forward to your reply

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. I think there are mainly two reasons. The sky is smooth but not static. As the camera zooms out, the pixels of sky roughly move down. Secondly, current flow estimators predict flow at 1/8 resolution and have a up-sampling layer. This up-sampling operation usually have a clear block pattern especially in smooth/texture-less areas. But from my experience, this block pattern is visually clear but minor in terms of the flow values. You can try more examples and let me know if there are other issues.
