### ISSUE TITLE
Is it possible to output flow  in .flo format? 

### ISSUE THREAD

**Issue by MichalTurek** [XiaoyuShi97/VideoFlow#15]
Hi, I was wondering if VideoFlow supports to output .flo instead of .png files? Also if not, then what are 3 channels in output pngs?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. Of course, the 3 channels of the pngs are mapped from the original two-channel flow values for better visualization. As shown in this line, https://github.com/XiaoyuShi97/VideoFlow/blob/main/inference.py#L38, the flow_pre is the raw flow values you want. Let me know if there are other questions.

**Comment by XiaoyuShi97** [comment]
PNG are only for visualization. The two dimensional flow are what we actually use and have no quality loss.
