### ISSUE TITLE
Generalization error on KITTI

### ISSUE THREAD

**Issue by DQiaole** [XiaoyuShi97/VideoFlow#16]
Hi, thanks for sharing your impressive work.  I have downloaded the **MOF_things.pth** and changed `_CN.model` of `configs/multiframes_sintel_submission.py` accordingly. But after running command `python -u evaluate_MOFNet.py --dataset=kitti`, I get `Validation KITTI: 4.284974, 15.392534`, which is much worse than the results reported in the paper. How can I get the generalization results on KITTI(train) of Table 1 in the paper?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. The Twins encoder is sensitive to resolution in the things stage, so we follow FlowFormer to train another model on resolution of 288*960 with noise augmentation. I will update that model soon.

**Comment by XiaoyuShi97** [comment]
Hi. I have updated the 288*960 version. Please have a try.

**Comment by DQiaole** [comment]
Hi, thanks for sharing the model. I can now get similar results as yours.
