### ISSUE TITLE
Question on training code

### ISSUE THREAD

**Issue by mazeyu** [XiaoyuShi97/VideoFlow#17]
Great work. I am wondering how you get the bidirectional ground truth from datasets like Sintel and where in the code do you use it as I see "oneside=True" everywhere. Thanks!

**Comment by ZhouQianang** [comment]
I have the same question, why don't have code like "flow2 = -flow2" to inverse the ground truth

**Comment by mazeyu** [comment]
I remember the author mentioned they mixed data with single-direction and both-direction to train. "flow2 = -flow2" will not work because of occlusion.
