### ISSUE TITLE
KITTI multi-view set

### ISSUE THREAD

**Issue by qianyu0220** [XiaoyuShi97/VideoFlow#2]
Thank you for your impressive VideoFlow!

Since the original KITTI is based on two-frame only, could you share your multi-frame/view KITTI data? Thanks!

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. You can find the data on the official KITTI  website.  https://www.cvlibs.net/datasets/kitti/eval_scene_flow.php. The entry is "[Download multi-view extension (20 frames per scene) (14 GB)](https://www.cvlibs.net/datasets/kitti/user_login.php)"
