### ISSUE TITLE
Consultation on color coding of output images

### ISSUE THREAD

**Issue by jdyjjj** [XiaoyuShi97/VideoFlow#20]
Hello,

I'm new to optical flow and using inference.py for my image processing. I'm struggling to interpret the colors in the output images, specifically regarding motion direction and speed. Could you please provide some guidance or documentation on how to read these color mappings? If you could give me some help, I would be extremely grateful.

Thank you!

**Comment by XiaoyuShi97** [comment]
![微信截图_20231214184640](https://github.com/XiaoyuShi97/VideoFlow/assets/25840016/0595219a-b480-4810-abed-ebef077ba603)

**Comment by XiaoyuShi97** [comment]
Basically, white means static and purer color represents higher speed. For example, pure blue means moveing to the left.

**Comment by jdyjjj** [comment]
Thank you very much for your patient reply. I understand now. Another thing I would like to know is that there is no specific data correspondence between the orientation and color in the picture you replied to me? If so, where can I get it from? Thank you very much again for your reply.

**Comment by XiaoyuShi97** [comment]
![image](https://github.com/XiaoyuShi97/VideoFlow/assets/25840016/c5db1cc7-277c-4790-bd7d-7f4700f61332)
I am not sure if I understand you correctly. There is a mapping between color and direction. Orange means moving to the right, blue to the left, and so on.

**Comment by jdyjjj** [comment]
thank you
