### ISSUE TITLE
CUDA out of memory when running inference.py

### ISSUE THREAD

**Issue by jdyjjj** [XiaoyuShi97/VideoFlow#21]
I'm very sorry to bother you. I have followed all the settings previously issued to reduce memory, but still CUDA out of memory. I would like to inquire if there is a way to run inference.py with multiple GPUs to avoid CUDA out of memory? Any response from you will be of great help to me, and I look forward to your help.
![image](https://github.com/XiaoyuShi97/VideoFlow/assets/73057174/9d7376c8-385c-4323-9da0-eb8098ad5dd9)

**Comment by XiaoyuShi97** [comment]
Hi. How many images do you have during inference? If the number is too large, you can split them into overlapped clips.

**Comment by jdyjjj** [comment]
10 1280 * 980 images

**Comment by XiaoyuShi97** [comment]
Maybe that's too much. You may consider take 5 images at once.

**Comment by jdyjjj** [comment]
If I only need flow images from front to back, is there a way to reduce memory usage?

**Comment by XiaoyuShi97** [comment]
Unfortunately, the bi-directinal features are concatenated along the channel dimension and therefore cannot be divided.
