### ISSUE TITLE
About evaluating on the Sintel dataset

### ISSUE THREAD

**Issue by LowSingVz** [XiaoyuShi97/VideoFlow#22]
Hello, I think my question is a bit low-level. I'm very sorry if it bothers you. I tried to make changes to the network and hoped to upload the evaluation results on the Sintel dataset to the official website. However, I was unable to successfully register an account and the webpage kept prompting me with "Domain not enabled." I don't know what caused this. I wrote an email to the official website of the Sintel dataset but did not respond. Please forgive my ignorance.

**Comment by XiaoyuShi97** [comment]
Hi, no worry. The website manager will email you to ask for your more detailed information and then enable your account. Sometimes the reply is not prompt.

**Comment by fangfang11-plog** [comment]
I'm facing the same issue, and it has been two months now. Is there any other way to contact the website manager?

**Comment by LowSingVz** [comment]
用官网提供的邮件地址联系管理员就可以了，通常会在第二天收到回复，希望对您有帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoyuShi97/VideoFlow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月13日(星期天) 下午5:04
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoyuShi97/VideoFlow] About evaluating on the Sintel dataset (Issue #22)





 
I'm facing the same issue, and it has been two months now. Is there any other way to contact the website manager?

**Comment by fangfang11-plog** [comment]
你好，按照你的方法，我重新申请，但是仍未收到回复

**Comment by lovean1** [comment]
> 用官网提供的邮件地址联系管理员就可以了，通常会在第二天收到回复，希望对您有帮助！
> […](#)
麻烦问一下，请问您用的是国内教育邮箱还是qq邮箱这种商业邮箱，我昨天用教育邮箱发邮件暂时还没回我，我在想是否是教育邮箱的问题
