### ISSUE TITLE
Computing resource

### ISSUE THREAD

**Issue by AMiaoJF** [XiaoyuShi97/VideoFlow#3]
Good job! What kind of equipment and how many days does it take to use your published training strategy? In a closed issue, the answer is not very detailed, please allow me to ask one more time.

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. It takes about 2.5 days to finish the things stage on v100 machine. As Sintel stage need much fewer iterations, it only takes ~1 day. Let me know if you have other questions.
