### ISSUE TITLE
nan value

### ISSUE THREAD

**Issue by KouseiHongqing** [XiaoyuShi97/VideoFlow#4]
Good job! 

I have a question. When I train the MOF model, I often encounter 'nan' values. Is this normal?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. It happens sometimes when using mixed precision training. Could you please try to train in full-precision (i.e. in things_multiframes.py, set both _CN.mixed_precision and _CN.MOFNetStack.mixed_precision to be False). Let me know if there are further problems.
