### ISSUE TITLE
long sequences

### ISSUE THREAD

**Issue by ygreg9** [XiaoyuShi97/VideoFlow#5]
First of all thanks for this excellent work! I am a physics researcher (fluid mechanics) and am currently investigating how the measure of optical flow can help extract measurements on experimental videos. Thus, I am only interested in the inference module, using the Sintel pretrained model. 

I managed to configure the code so that computations can run on my images but I am facing a memory problem whenever the image sequences are too long. If I understand correctly, the flow is computed over 5 images but the whole image sequence is staked and then fed to the model. Is there a clever way to send the images by group of 5 and to collect the results progressively instead of in one huge variable?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. In fact, the MOF model is trained over 5 images, but during inference, it predicts the optical flows of all input frames (of arbitrary length). So you can cut your video frames into several short clips, depending on your GPU limit, and predict the flows clip by clip. Let me know if you have other problems.

**Comment by ygreg9** [comment]
I will indeed try to cut my sequence into something smaller. However, I assume that during the inference, the model is not processing all the frames of the sequence at the same time. So, if I cut the video in shorter clips, won't there be continuity issues at the borders of the different clips? Do I need overlapping images between two consecutive clips, and if so, how many?

**Comment by XiaoyuShi97** [comment]
If the inputs are N frames, you will get (N-2)*2 flow maps. N-2 means only the middle (N-2) frames have prediction and *2 is for bi-direction. Say, you have a 10 frames and you want to cut them into clips of length 6. Then the two clips should be [1-6], [5-10].

**Comment by XiaoyuShi97** [comment]
By the way, if you also want the flows for the first and last frame, you can copy the first and last frames (i.e. padding). For instance, you have 6 images, then your input should be, I_1, I_1, I_2, I_3, I_4, I_5, I_6, I_6. This way, you can get flow(1->2) and flow(6->5). Let me know if there is anything unclear.
