### ISSUE TITLE
future flow prediction

### ISSUE THREAD

**Issue by realimposter** [XiaoyuShi97/VideoFlow#6]
Amazing work thanks for sharing. what would happen if a model was trained with the same 3 input frames but with the output flow from the 3rd->4th frame? could it potentially do future flow prediction?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. I think it should work. I guess, it is more natural and likely better to inherit the pretrained model and add additional head/channels for the future flow prediction during finetuning.
