### ISSUE TITLE
ModuleNotFoundError: No module named 'configs.kitti'

### ISSUE THREAD

**Issue by pokameng** [XiaoyuShi97/VideoFlow#8]
Hello
@XiaoyuShi97  
ModuleNotFoundError: No module named 'configs.kitti' 
![image](https://github.com/XiaoyuShi97/VideoFlow/assets/47957015/ab9743bc-39b1-40ce-9bb4-48f37ba7ae3b)

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. Please check the update. Let me know if there are other problems.

**Comment by pokameng** [comment]
> Hi, thanks for your interest in our work. Please check the update. Let me know if there are other problems.

Hi，thanks for your reply !
Can you tell me  the dataset kitti like this :training/flow_occ/000017_10.png  how to download?

**Comment by XiaoyuShi97** [comment]
Hi. in this https://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=flow page, click the [Download multi-view extension (20 frames per scene) (14 GB)](https://www.cvlibs.net/datasets/kitti/user_login.php) entry.

**Comment by pokameng** [comment]
> Hi. in this https://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=flow page, click the [Download multi-view extension (20 frames per scene) (14 GB)](https://www.cvlibs.net/datasets/kitti/user_login.php) entry.

You mean I need to download these four sources?
![image](https://github.com/XiaoyuShi97/VideoFlow/assets/47957015/5c3bb253-4ba1-43a3-ab35-43ec16133dee)

**Comment by XiaoyuShi97** [comment]
Only the third one (14GB).

**Comment by pokameng** [comment]
> Only the third one (14GB).
I have download this ,but I find that training/flow_occ/000199_10.png doesn't in the third one.
I find the training/flow_occ/000199_10.png in the first .
![image](https://github.com/XiaoyuShi97/VideoFlow/assets/47957015/98d3c281-a56c-4284-97a9-0e57bcee3202)

**Comment by XiaoyuShi97** [comment]
Ohhh. Seems the third one only contains the images while the GT flows are in the first one. I forget as I downloaded this data long time ago. So you are right and please download both the first and third ones.

**Comment by pokameng** [comment]
> 

ok  thanks ! I have solved this problem!
By the way , can we share with wechat?

**Comment by XiaoyuShi97** [comment]
Sure. shixiaoyushifo
