### ISSUE TITLE
video test

### ISSUE THREAD

**Issue by cab0625** [XiaoyuShi97/VideoFlow#9]
Please explain how you conduct video testing?

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. What does "video testing" refer to? Do you mean inference or the testing settings on the sintel benchmark?

**Comment by cab0625** [comment]
Thank you very much for your timely reply and guidance. The video test I mentioned means that it can be tested on inference. Do you have relevant codes that can be used directly?

**Comment by XiaoyuShi97** [comment]
I see. Please refer to inference.py for inference code.

**Comment by cab0625** [comment]
Isn't the code primarily for consecutive frames as images? How can it be adapted to perform video stream inference similar to your demo?

**Comment by XiaoyuShi97** [comment]
I first convert video to images using https://stackoverflow.com/questions/33311153/python-extracting-and-saving-video-frames

**Comment by cab0625** [comment]
Okay, thank you very much for your patient explanations！
